// @ts-nocheck
import React,{useEffect,useMemo,useState}from'react';
import{CalendarDays,Flame,TrendingUp,Diamond,LineChart,SlidersVertical,Info,Search,Grid2X2,Menu,ArrowDownRight,ArrowUpRight,Bookmark,Share2,ChevronRight,Zap,ShoppingBag,Wallet,MapPin,Phone,Clock3,Gavel,Package,MessageCircle,Plus,CheckCircle2}from'lucide-react';
import {Header} from '../../components';

const dashboardSections:any[][]=[['participating','참여 중인 경매','현재 참여 중인 경매를 확인하세요.',[0,1,2,3,4,5]],['favorites','찜한 카드','관심 목록에 저장한 카드입니다.',[2,4,7]],['recent-wins','최근 나의 낙찰','최근 낙찰받은 카드와 낙찰가를 확인하세요.',[3,5,8]]];

const cards:any[][]=[
['피카츄 P 메가 에볼루션 프로모카드',138000,2.7,'gold','368'],['피카츄 P 스칼렛&바이올렛 프로모 카드',135000,8.9,'gold','105'],['메타몽의 타임 캡슐 프로모 카드 메타몽',415000,1.2,'water','97'],['피카츄 P 스칼렛&바이올렛 프로모 카드',171000,5,'multi','97'],['피카츄 25주년 기념 컬렉션',115000,0.9,'dark','83'],['피카츄 P 유나가바 소트&실드 프로모 카드',571000,0.4,'sketch','76'],['피카츄 P 스칼렛&바이올렛 프로모 카드',116000,1.9,'gold','71'],['피카츄 P 스칼렛&바이올렛 프로모 카드',165000,8.3,'gold','68'],['고라파덕 AR 메가 드림 ex',157000,4.7,'water','62'],['리자몽 ex 스페셜 아트 경매 카드',289000,6.2,'multi','54']];

const trades:any[][]=[[137000,'2시간 전'],[122000,'7시간 전'],[128000,'8시간 전'],[130000,'9시간 전'],[139000,'11시간 전']];

function useAuctionNow(){const[now,setNow]=useState(Date.now());useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]);return now}

const cardGrades=[10,9,8,7,6,5,4,3,2,1];
const auctionStartPrices=[42000,65000,250000,90000,70000,350000,60000,95000,80000,150000];
const auctionBidIncrements=[1000,1000,5000,1000,1000,5000,1000,1000,1000,5000];

function formatRemaining(endAt,now){const total=Math.max(0,Math.ceil((endAt-now)/1000));if(!total)return'경매 종료';const hours=Math.floor(total/3600),minutes=Math.floor(total%3600/60),seconds=total%60;return hours?`${String(hours).padStart(2,'0')}:${String(minutes).padStart(2,'0')}:${String(seconds).padStart(2,'0')}`:`${String(minutes).padStart(2,'0')}:${String(seconds).padStart(2,'0')}`}

const auctionDurations=[12*60+48,43*60+20,18*60+4,2*60*60+14*60+31,7*60+12,5*60*60+18*60+4,36*60+9,84*60+46,3*60*60+2*60+27,6*60*60+31*60+9];

const auctionStartedAt=Date.now();

const auctionEndsAt=auctionDurations.map(seconds=>auctionStartedAt+seconds*1000);

let mockFavoriteCards=[2,4,7];

function readFavorites(){return[...mockFavoriteCards]}

function useFavorites():[number[],(cardIndex:number)=>void]{const[favorites,setFavorites]=useState(readFavorites);useEffect(()=>{const sync=()=>setFavorites(readFavorites());window.addEventListener('favorites-change',sync);return()=>window.removeEventListener('favorites-change',sync)},[]);const toggle=(cardIndex:number)=>{mockFavoriteCards=mockFavoriteCards.includes(cardIndex)?mockFavoriteCards.filter(index=>index!==cardIndex):[...mockFavoriteCards,cardIndex];window.dispatchEvent(new Event('favorites-change'))};return[favorites,toggle]}

function FavoriteButton({cardIndex}){const[favorites,toggle]=useFavorites(),active=favorites.includes(cardIndex);return <button className={'favorite-button '+(active?'active':'')} aria-label={active?'찜 해제':'찜하기'} aria-pressed={active} onClick={event=>{event.preventDefault();event.stopPropagation();toggle(cardIndex)}}><Bookmark/></button>}

function CardArt({theme}){return <div className={'mini-card '+theme}><i>HP 70</i><span>●</span><small>POKÉMON</small></div>}

function MiniSpark({path}){return <svg viewBox="0 0 60 42" preserveAspectRatio="none" aria-hidden="true"><path d={path}/></svg>}

const auctionSparkPaths=['M2 37 L10 37 L10 33 L18 33 L18 28 L27 28 L27 22 L36 22 L36 16 L46 16 L46 10 L58 10','M2 36 L8 36 L8 34 L17 34 L17 29 L25 29 L25 25 L34 25 L34 19 L43 19 L43 13 L51 13 L51 7 L58 7','M2 38 L13 38 L13 32 L22 32 L22 27 L31 27 L31 21 L41 21 L41 17 L49 17 L49 11 L58 11','M2 35 L9 35 L9 31 L20 31 L20 26 L29 26 L29 20 L39 20 L39 15 L48 15 L48 9 L58 9'];

function AuctionBidDialog({card,onClose,bidState='new'}){const[name,price]=card,wallet=850000,minimum=price+1000,[amount,setAmount]=useState(minimum),options=[minimum,minimum+4000,minimum+9000],amountValue=Number(amount),belowMinimum=amount===""||amountValue<minimum,insufficient=amountValue>wallet,locked=bidState==='leading';return <div className="bid-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="bid-dialog" role="dialog" aria-modal="true" aria-label={`${name} 입찰`}><button className="bid-close" onClick={onClose} aria-label="닫기">×</button><small>실시간 카드 경매</small><h2>입찰하기</h2><p className="bid-card-name">{name}</p>{locked&&<div className="bid-leading-notice"><CheckCircle2/><span><b>현재 최고가 입찰 중입니다.</b><small>입찰 현황은 확인할 수 있지만 추가 입찰은 제한됩니다.</small></span></div>}<div className="bid-wallet"><span><Wallet/>전자지갑 포인트</span><strong>{wallet.toLocaleString()}P</strong></div><div className="bid-current"><span>현재 경매가<b>{price.toLocaleString()}원</b></span><span>최소 입찰가<b>{minimum.toLocaleString()}원</b></span></div><h3>입찰가 선택</h3><div className="bid-options">{options.map(value=><button key={value} className={amountValue===value?'active':''} disabled={locked} onClick={()=>setAmount(value)}>{value.toLocaleString()}원</button>)}</div><label>직접 입력<div className={belowMinimum?'invalid':''}><input disabled={locked} type="number" step="1000" value={amount} onChange={e=>setAmount(e.target.value)}/><span>원</span></div>{belowMinimum&&<small className="bid-minimum-error">최소 입찰가 {minimum.toLocaleString()}원 이상 입력해 주세요.</small>}</label><section className="bid-history"><div className="bid-history-head"><h3>경매 입찰 내역</h3><span>최근 5건</span></div><div className="bid-history-list">{trades.map((trade,i)=><div className="bid-history-row" key={trade[0]+trade[1]}><span><b>PSA 10</b><small>{i===0?'최고 입찰':'입찰 완료'}</small></span><strong>{trade[0].toLocaleString()}원</strong><time>{trade[1]}</time></div>)}</div></section><div className="bid-balance"><span>입찰 후 잔여 포인트</span><b>{Math.max(0,wallet-(amountValue||0)).toLocaleString()}P</b></div>{insufficient&&<p className="bid-error">전자지갑 포인트가 부족합니다.</p>}<button className="bid-submit" disabled={belowMinimum||insufficient||locked} onClick={onClose}>{locked?'현재 최고가 입찰 중':amountValue.toLocaleString()+'원 입찰하기'}</button></section></div>}

function MarketCard({card,index,onOpen,hideDetails=false,deliveryAction=false,detailPath="cards"}){const[name,price,,theme,trades]=card,now=useAuctionNow(),[bidOpen,setBidOpen]=useState(false),cardIndex=Math.max(0,cards.indexOf(card)),grade=cardGrades[cardIndex]||10,remaining=formatRemaining(auctionEndsAt[cardIndex],now),ended=remaining==='경매 종료',bidState=cardIndex%3===0?'leading':cardIndex%3===1?'outbid':'new',myBid=Math.max(1000,price-(bidState==='outbid'?3000:0)),startPrice=auctionStartPrices[cardIndex]??price,bidIncrement=auctionBidIncrements[cardIndex]??1000,increase=price-startPrice,increaseRate=startPrice>0?increase/startPrice*100:0;const showDetails=()=>onOpen?onOpen(card,cardIndex):(window.location.href='/'+detailPath+'/'+(cardIndex+1)),bidLabel=deliveryAction?'배송 신청하기':ended?'경매 종료':bidState==='leading'?'최고가 입찰 중':bidState==='outbid'?'상회 입찰 필요':'입찰하기';return <article className={'card-tile up'+(ended?' ended':'')}><FavoriteButton cardIndex={cardIndex}/><CardArt theme={theme}/><div><div className="card-meta"><span><span className="grade">PSA {grade}</span><span className="grade">JP</span></span><span className="auction-countdown"><Clock3/>{remaining}{!ended&&' 남음'}</span></div><h3>{name}</h3><small>현재 경매가</small><div className="tile-price"><strong>{price.toLocaleString()}원</strong><em>시작가 대비 +{increaseRate.toFixed(1)}%</em></div><div className="auction-card-info"><span>시작가<b>{startPrice.toLocaleString()}원</b></span><span>누적 상승액<b className="increase-value">+{increase.toLocaleString()}원</b></span><span>다음 최소 입찰가<b>{(price+bidIncrement).toLocaleString()}원</b></span><span>총 입찰<b>{Number(trades).toLocaleString()}회</b></span></div><div className="card-actions">{!hideDetails&&<button className="card-detail-button" onClick={showDetails}>상세보기</button>}<button className={'card-bid-button '+(deliveryAction?'delivery':bidState)} disabled={!deliveryAction&&ended} onClick={()=>deliveryAction?window.alert('배송 신청이 접수되었습니다.'):setBidOpen(true)}>{!deliveryAction&&bidState==='leading'?<><CheckCircle2/><span><b>내가 최고가 입찰 중</b><small>현재 1위 · 입찰 현황 보기</small></span></>:<><b>{bidLabel}</b>{!deliveryAction&&!ended&&bidState==='outbid'&&<small>내 입찰 {myBid.toLocaleString()}원</small>}</>}</button></div></div>{bidOpen&&!deliveryAction&&<AuctionBidDialog card={card} bidState={bidState} onClose={()=>setBidOpen(false)}/>}</article>}

function DashboardView({query,setQuery}){const[activeFilter,setActiveFilter]=useState('participating'),section=dashboardSections.find(([id])=>id===activeFilter);const[id,title,copy,indexes]=section,visibleCards=indexes.map(index=>cards[index]).filter(card=>card[0].includes(query));return <><div className="cards-dash-title"><div><small>MY PAGE</small><h1>경매 대시보드</h1><p>내 카드 경매 현황을 빠르게 확인하세요.</p></div><a className="dashboard-all-auctions" href="/auction">전체 카드 경매 <ChevronRight/></a></div><label className="card-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="내 경매 카드 검색..."/></label><div className="dashboard-filters" role="tablist" aria-label="대시보드 목록 필터">{dashboardSections.map(([sectionId,sectionTitle])=><button key={sectionId} role="tab" aria-selected={activeFilter===sectionId} className={activeFilter===sectionId?'active':''} onClick={()=>setActiveFilter(sectionId)}>{sectionTitle}</button>)}</div><section id={id} className={'cards-dash-section '+(id==='participating'?'participating-section':'')}><div className="cards-dash-section-head"><div><h2>{title}</h2><p>{copy}</p></div></div><div className="card-grid">{visibleCards.map(card=><MarketCard card={card} index={cards.indexOf(card)} deliveryAction={id==='recent-wins'} key={card[0]+cards.indexOf(card)}/>)}</div></section></>}

export default function AuctionDashboardPage(){const[query,setQuery]=useState('');return <div className="cards-mypage standalone-dashboard enhanced-cards"><Header/><main><DashboardView query={query} setQuery={setQuery}/></main></div>}
