// @ts-nocheck
import React,{useEffect,useMemo,useState}from'react';
import{CalendarDays,Flame,TrendingUp,Diamond,LineChart,SlidersVertical,Info,Search,Grid2X2,Menu,ArrowDownRight,ArrowUpRight,Bookmark,Share2,ChevronRight,Zap,ShoppingBag,Wallet,MapPin,Phone,Clock3,Gavel,Package,MessageCircle,Plus,CheckCircle2}from'lucide-react';
import {Header} from '../../components';

function Insight({type,title,value,change=null,note,filter}){const Icon=type==='fire'?Flame:type==='rise'?TrendingUp:Diamond;return <article className={'insight '+type+' insight-action'} role="link" tabIndex={0} onClick={()=>window.location.href=`/auction?filter=${filter}`} onKeyDown={e=>(e.key==='Enter'||e.key===' ')&&(window.location.href=`/auction?filter=${filter}`)}><div className="insight-title"><span><Icon/></span><b>{title}</b></div><div className="insight-value"><strong>{value}<small>종</small></strong>{change&&<em>{change}</em>}</div><p>{note}</p></article>}

const marketPath='M0 198 L34 198 L34 188 L78 188 L78 174 L116 174 L116 158 L161 158 L161 142 L205 142 L205 126 L251 126 L251 110 L294 110 L294 95 L342 95 L342 79 L389 79 L389 64 L437 64 L437 49 L486 49 L486 35 L535 35 L535 23 L586 23 L586 12 L650 12';

function Chart(){return <div className="chart-wrap"><div className="axis left"><span>28만</span><span>23만</span><span>19만</span><span>15만</span></div><div className="bars">{Array.from({length:31},(_,i)=><i key={i} style={{height:55+(i*17%85)}}/> )}</div><svg className="market-line" viewBox="0 0 650 220" preserveAspectRatio="none"><defs><linearGradient id="fade" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#19b86a" stopOpacity=".16"/><stop offset="1" stopColor="#19b86a" stopOpacity="0"/></linearGradient></defs><path className="chart-area" d={marketPath+' L650 220 L0 220Z'}/><path className="chart-stroke" d={marketPath}/></svg><div className="axis right"><span>400건</span><span>300건</span><span>200건</span><span>100건</span><span>0건</span></div><div className="dates"><span>06/19</span><span>06/24</span><span>06/29</span><span>07/04</span><span>07/09</span><span>07/14</span><span>07/19</span></div><div className="legend"><span className="green-line"/>경매가(원)<span className="gray-box"/>입찰량(건)</div></div>}

const gainers:any[][]=[
  ['고라파덕 P 스칼렛&바이올렛 프...',199000,'+42.1%','water','입찰 8건','M4 20 L13 25 L22 8 L31 34 L40 38 L51 5'],
  ['N의 제크로무AR 메가 드림 ex',92000,'+15.0%','dark','입찰 64건','M3 20 L9 29 L14 5 L19 23 L24 12 L29 31 L34 20 L39 28 L44 19 L49 29 L54 17'],
  ['피카츄 AR 포켓몬 카드 151',238000,'+15.0%','multi','입찰 26건','M2 9 L8 24 L15 11 L21 28 L27 15 L33 22 L39 8 L45 31 L52 25 L57 7'],
  ['메가 개굴닌자 ex MUR 닌자 스...',1744000,'+10.7%','gold','입찰 5건','M2 8 Q12 37 22 23 T40 25 T58 20'],
  ['릴리에의 에리본 AR 배틀 파트너즈',98000,'+10.1%','sketch','입찰 24건','M2 23 L7 11 L12 28 L18 6 L25 25 L31 16 L38 28 L45 28 L51 34 L58 15'],
];

function CardArt({theme}){return <div className={'mini-card '+theme}><i>HP 70</i><span>●</span><small>POKÉMON</small></div>}

function MiniSpark({path}){return <svg viewBox="0 0 60 42" preserveAspectRatio="none" aria-hidden="true"><path d={path}/></svg>}

function Ranking({onOpen}){return <aside><h2>전일 상승 Top 5</h2><div className="ranking">{gainers.map((g,i)=><div className="rank rank-action" key={g[0]} role="button" tabIndex="0" onClick={()=>window.location.href='/cards/'+(i+1)} onKeyDown={e=>(e.key==='Enter'||e.key===' ')&&(window.location.href='/cards/'+(i+1))}><b className="number">{i+1}</b><CardArt theme={g[3]}/><div className="rank-info"><p>{g[0]}</p><strong>{g[1].toLocaleString()}원 <em>{g[2]}</em></strong><small>{g[4]}</small></div><MiniSpark path={g[5]}/></div>)}</div></aside>}

const trades:any[][]=[[137000,'2시간 전'],[122000,'7시간 전'],[128000,'8시간 전'],[130000,'9시간 전'],[139000,'11시간 전']];

const cardGrades=[10,9,8,7,6,5,4,3,2,1];

function CardDetailModal({selection,onClose}){const{card,index}=selection,[name,price,change,,trades]=card,grade=cardGrades[index]||10;return <div className="card-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="card-modal" role="dialog" aria-modal="true" aria-label={`${name} 경매 상세 정보`}><button className="modal-close" onClick={onClose} aria-label="닫기">×</button><aside className="modal-product"><img src="/assets/pikachu-promo-card.png" alt={name}/><div><span className="grade">PSA {grade}</span><span className="grade">JP</span><h2>{name}</h2><p>Pokemon TCG Collectible Auction Card...</p><small>경매번호&nbsp; AUCTION020-M-P_JP</small></div><a href={`/auction/${index+1}`}>경매 상세보기</a></aside><div className="modal-market up"><div className="modal-price"><small>현재 경매가 <Info/></small><h1>{price.toLocaleString()}원 <em>+{change.toFixed(1)}%</em></h1></div><div className="instant-prices"><span>다음 최소 입찰가<b>{(price+1000).toLocaleString()}원</b></span><span>현재 최고 입찰가<b>{price.toLocaleString()}원</b></span></div><div className="modal-chart-title"><h2>30일 경매가 · 입찰량</h2><small>입찰 시점 기준</small></div><div className="modal-chart"><div className="modal-bars">{Array.from({length:30},(_,i)=><i key={i} style={{height:35+(i*23%75)}}/> )}</div><svg viewBox="0 0 650 220" preserveAspectRatio="none"><path className="modal-area" d={marketPath+' L650 220 L0 220Z'}/><path className="modal-line" d={marketPath}/></svg><div className="modal-dates"><span>06/19</span><span>06/24</span><span>06/29</span><span>07/04</span><span>07/09</span><span>07/14</span><span>07/19</span></div></div><div className="modal-stats"><span>1일 상승<b>+{change.toFixed(1)}%</b></span><span>7일 상승<b>+{(change*3).toFixed(1)}%</b></span><span>30일 상승<b>+{(change*13).toFixed(1)}%</b></span><span>30일 입찰<strong>{trades}건</strong></span></div></div></section></div>}

export default function DashboardPage(){const[mode,setMode]=useState('line'),[selection,setSelection]=useState(null);const openRanking=(g,i)=>setSelection({card:[g[0],g[1],parseFloat(g[2]),g[3],g[4].replace(/[^0-9]/g,'')||'0'],index:i});return <><Header/><main><div className="home-overview-row"><div><p className="intro">현재 진행 중인 PSA 10 등급 카드 경매의 실시간 입찰 현황입니다.</p><div className="date"><CalendarDays/> 실시간 경매 기준</div></div><div className="home-cta-group"><a className="home-market-cta" href="/cards">카드 시세 보러가기</a><a className="home-auction-cta primary" href="/auction">경매하기 <ChevronRight/></a><a className="home-sell-cta" href="/sell">판매하기 <ChevronRight/></a></div></div><div className="section-title-row"><h2 className="section-title">경매 인사이트</h2><a className="section-card-link" href="/auction">카드보기 <ChevronRight/></a></div><section className="insights"><Insight type="fire" filter="bidding" title="경매가 상승" value="14" change="+9.4%" note="신규 입찰로 경매가 상승"/><Insight type="rise" filter="bidding" title="신규 입찰" value="8" change="+10.2%" note="최근 추가 입찰 발생"/><Insight type="volume" filter="favorites" title="입찰 활발" value="1" note="입찰량이 빠르게 증가 중"/></section><section className="dashboard"><div className="market"><h2>30일 경매가 · 입찰량</h2><div className="market-panel"><div className="metrics"><div><span>현재 경매가 평균 <Info/></span><strong>164,063원</strong></div><div><span>1일 상승</span><b>+3.7%</b></div><div><span>7일 상승</span><b>+12.1%</b></div><div><span>30일 상승</span><b>+30.2%</b></div><div><span>30일 총 입찰</span><strong>4,858건</strong></div><div className="switch"><button className={mode==='line'?'on':''} onClick={()=>setMode('line')} aria-label="경매가 그래프"><LineChart/></button><button className={mode==='bar'?'on':''} onClick={()=>setMode('bar')} aria-label="입찰량 그래프"><SlidersVertical/></button></div></div><Chart/></div></div><Ranking onOpen={openRanking}/></section></main>{selection&&<CardDetailModal selection={selection} onClose={()=>setSelection(null)}/>}<footer/></>}
