// @ts-nocheck
import React,{useEffect,useMemo,useState}from'react';
import{CalendarDays,Flame,TrendingUp,Diamond,LineChart,SlidersVertical,Info,Search,Grid2X2,Menu,ArrowDownRight,ArrowUpRight,Bookmark,Share2,ChevronRight,Zap,ShoppingBag,Wallet,MapPin,Phone,Clock3,Gavel,Package,MessageCircle,Plus,CheckCircle2}from'lucide-react';
import {Header} from '../../components';

const cards:any[][]=[
['피카츄 P 메가 에볼루션 프로모카드',138000,2.7,'gold','368'],['피카츄 P 스칼렛&바이올렛 프로모 카드',135000,8.9,'gold','105'],['메타몽의 타임 캡슐 프로모 카드 메타몽',415000,1.2,'water','97'],['피카츄 P 스칼렛&바이올렛 프로모 카드',171000,5,'multi','97'],['피카츄 25주년 기념 컬렉션',115000,0.9,'dark','83'],['피카츄 P 유나가바 소트&실드 프로모 카드',571000,0.4,'sketch','76'],['피카츄 P 스칼렛&바이올렛 프로모 카드',116000,1.9,'gold','71'],['피카츄 P 스칼렛&바이올렛 프로모 카드',165000,8.3,'gold','68'],['고라파덕 AR 메가 드림 ex',157000,4.7,'water','62'],['리자몽 ex 스페셜 아트 경매 카드',289000,6.2,'multi','54']];

const cardGrades=[10,9,8,7,6,5,4,3,2,1];

function useAuctionNow(){const[now,setNow]=useState(Date.now());useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]);return now}

function formatRemaining(endAt,now){const total=Math.max(0,Math.ceil((endAt-now)/1000));if(!total)return'경매 종료';const hours=Math.floor(total/3600),minutes=Math.floor(total%3600/60),seconds=total%60;return hours?`${String(hours).padStart(2,'0')}:${String(minutes).padStart(2,'0')}:${String(seconds).padStart(2,'0')}`:`${String(minutes).padStart(2,'0')}:${String(seconds).padStart(2,'0')}`}

const auctionDurations=[12*60+48,43*60+20,18*60+4,2*60*60+14*60+31,7*60+12,5*60*60+18*60+4,36*60+9,84*60+46,3*60*60+2*60+27,6*60*60+31*60+9];

const auctionStartedAt=Date.now();

const auctionEndsAt=auctionDurations.map(seconds=>auctionStartedAt+seconds*1000);

const trades:any[][]=[[137000,'2시간 전'],[122000,'7시간 전'],[128000,'8시간 전'],[130000,'9시간 전'],[139000,'11시간 전']];

function AuctionBidDialog({card,onClose,bidState='new'}){const[name,price]=card,wallet=850000,minimum=price+1000,[amount,setAmount]=useState(minimum),options=[minimum,minimum+4000,minimum+9000],amountValue=Number(amount),belowMinimum=amount===""||amountValue<minimum,insufficient=amountValue>wallet,locked=bidState==='leading';return <div className="bid-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="bid-dialog" role="dialog" aria-modal="true" aria-label={`${name} 입찰`}><button className="bid-close" onClick={onClose} aria-label="닫기">×</button><small>실시간 카드 경매</small><h2>입찰하기</h2><p className="bid-card-name">{name}</p>{locked&&<div className="bid-leading-notice"><CheckCircle2/><span><b>현재 최고가 입찰 중입니다.</b><small>입찰 현황은 확인할 수 있지만 추가 입찰은 제한됩니다.</small></span></div>}<div className="bid-wallet"><span><Wallet/>전자지갑 포인트</span><strong>{wallet.toLocaleString()}P</strong></div><div className="bid-current"><span>현재 경매가<b>{price.toLocaleString()}원</b></span><span>최소 입찰가<b>{minimum.toLocaleString()}원</b></span></div><h3>입찰가 선택</h3><div className="bid-options">{options.map(value=><button key={value} className={amountValue===value?'active':''} disabled={locked} onClick={()=>setAmount(value)}>{value.toLocaleString()}원</button>)}</div><label>직접 입력<div className={belowMinimum?'invalid':''}><input disabled={locked} type="number" step="1000" value={amount} onChange={e=>setAmount(e.target.value)}/><span>원</span></div>{belowMinimum&&<small className="bid-minimum-error">최소 입찰가 {minimum.toLocaleString()}원 이상 입력해 주세요.</small>}</label><section className="bid-history"><div className="bid-history-head"><h3>경매 입찰 내역</h3><span>최근 5건</span></div><div className="bid-history-list">{trades.map((trade,i)=><div className="bid-history-row" key={trade[0]+trade[1]}><span><b>PSA 10</b><small>{i===0?'최고 입찰':'입찰 완료'}</small></span><strong>{trade[0].toLocaleString()}원</strong><time>{trade[1]}</time></div>)}</div></section><div className="bid-balance"><span>입찰 후 잔여 포인트</span><b>{Math.max(0,wallet-(amountValue||0)).toLocaleString()}P</b></div>{insufficient&&<p className="bid-error">전자지갑 포인트가 부족합니다.</p>}<button className="bid-submit" disabled={belowMinimum||insufficient||locked} onClick={onClose}>{locked?'현재 최고가 입찰 중':amountValue.toLocaleString()+'원 입찰하기'}</button></section></div>}

export default function DetailPage(){const id=Math.max(1,Number(window.location.pathname.split('/').filter(Boolean).pop())||1),index=(id-1)%cards.length,card=cards[index],[name,price,change,theme,tradeCount]=card,grade=cardGrades[index]||10,now=useAuctionNow(),remaining=formatRemaining(auctionEndsAt[index],now),minimumBid=price+1000,[bidOpen,setBidOpen]=useState(false);return <div className="detail-page auction-detail-page"><Header/><main className="auction-detail-shell"><div className="auction-detail-layout"><section className="auction-detail-product"><img src="/assets/pikachu-promo-card.png" alt={name}/><div className="detail-grades"><span className="grade">PSA {grade}</span><span className="grade">JP</span></div><h1>{name}</h1><p>Pokemon TCG Collectible Auction Card · Japanese Ver.</p><small>경매번호 AUCTION-{String(id).padStart(4,'0')}</small></section><section className="auction-bid-panel"><div className="auction-live-label"><i/> LIVE 경매 <span><Clock3/>{remaining}</span></div><div className="auction-current-price"><small>현재 입찰가</small><strong>{price.toLocaleString()}원</strong><em>+{change.toFixed(1)}%</em></div><div className="auction-bid-summary"><span>다음 최소 입찰가<b>{minimumBid.toLocaleString()}원</b></span><span>누적 입찰 수<b>{tradeCount}건</b></span><span>PSA 등급<b>PSA {grade}</b></span></div><div className="auction-wallet-summary"><span><Wallet/>보유 포인트</span><strong>850,000P</strong></div><button className="auction-detail-bid-button" disabled={remaining==='경매 종료'} onClick={()=>setBidOpen(true)}>{remaining==='경매 종료'?'경매 종료':minimumBid.toLocaleString()+'원부터 입찰하기'}</button><a className="auction-card-price-link" href={`/cards/${id}`}>카드 시세 상세 <ChevronRight/></a><section className="auction-detail-history"><h2>최근 입찰 내역</h2>{trades.map((trade,tradeIndex)=><div key={trade[0]+trade[1]}><span><b>{tradeIndex===0?'최고 입찰':'입찰 완료'}</b><small>{trade[1]}</small></span><strong>{trade[0].toLocaleString()}원</strong></div>)}</section></section></div><section className="auction-seller-post"><div className="auction-seller-heading"><div className="auction-seller-avatar">PC</div><span><small>경매 등록자</small><b>포켓컬렉터</b><em>거래 128회 · 신뢰도 98%</em></span></div><div className="auction-seller-content"><small>SELLER NOTE</small><h2>경매 상품 설명</h2><p>컬렉션 정리로 내놓는 {name} 카드입니다. 슬리브와 하드 케이스에 보관해 카드 상태가 깨끗하며, 사진에 보이는 실물 그대로 안전하게 포장해 보내드립니다.</p><dl><div><dt>상품 상태</dt><dd>PSA {grade} 케이스 보관 · 눈에 띄는 손상 없음</dd></div><div><dt>포함 구성</dt><dd>카드 본품, PSA 케이스, 보호 슬리브</dd></div><div><dt>배송 안내</dt><dd>낙찰 확인 후 2영업일 이내 완충 포장하여 발송</dd></div></dl><div className="auction-seller-notice"><Info/><span><b>입찰 전 확인해 주세요.</b><small>등록 사진과 설명을 충분히 확인한 뒤 입찰해 주세요. 낙찰 후 단순 변심으로 인한 취소는 어렵습니다.</small></span></div></div></section></main>{bidOpen&&<AuctionBidDialog card={card} onClose={()=>setBidOpen(false)}/>}</div>}
