// @ts-nocheck
import React,{useEffect,useMemo,useState}from'react';
import{CalendarDays,Flame,TrendingUp,Diamond,LineChart,SlidersVertical,Info,Search,Grid2X2,Menu,ArrowDownRight,ArrowUpRight,Bookmark,Share2,ChevronRight,Zap,ShoppingBag,Wallet,MapPin,Phone,Clock3,Gavel,Package,MessageCircle,Plus,CheckCircle2}from'lucide-react';
import {Header} from '../../components';

const viewNav:any[][]=[['account','계정 관리',[['회원 정보','profile-info'],['기본 배송지','shipping-address'],['연락처','phone-info'],['로그아웃','signout']]],['support','문의 및 신고',[['문의 / 유저 신고하기','admin-contact'],['문의 내역','support-history']]]];

function ThreeViewNav({view,onView,onScroll}){return <aside className="cards-dash-nav three-nav"><h1>마이 페이지</h1>{viewNav.map(([id,label,items])=><section key={id}><h2 className={view===id?'active':''} onClick={()=>onView(id)}>{label}</h2>{items.map(([text,target])=><button key={target} onClick={()=>view===id?onScroll(target):onView(id,target)}>{text}</button>)}</section>)}</aside>}

function SupportHistory({report}){return <section id="support-history" className="subview-card"><h2>{report?'신고 내역':'문의 내역'}</h2>{report?<><div className="subview-row"><span><b>경매 방해 행위 신고</b><small>2026.07.20 · 사용자 pokemon_bad</small></span><em className="complete">처리 완료</em></div><div className="subview-row"><span><b>부적절한 메시지 신고</b><small>2026.07.18 · 사용자 card_user12</small></span><em>검토 중</em></div></>:<><div className="subview-row"><span><b>배송지 변경이 가능한가요?</b><small>2026.07.19 · 배송 문의</small></span><em className="complete">답변 완료</em></div><div className="subview-row"><span><b>PSA 검수 기준 문의</b><small>2026.07.18 · 상품 문의</small></span><em>답변 대기</em></div></>}</section>}

function SupportView(){const[mode,setMode]=useState('inquiry');const report=mode==='report';return <div className="mypage-subview"><div className="subview-title"><small>MY PAGE</small><h1>문의 및 신고</h1><p>관리자 문의 또는 유저 신고를 접수할 수 있습니다.</p></div><div className="support-switch"><button className={!report?'active':''} onClick={()=>setMode('inquiry')}>관리자 문의하기</button><button className={report?'active':''} onClick={()=>setMode('report')}>유저 신고하기</button></div><section id="admin-contact" className="subview-card contact-form"><h2>{report?'유저 신고하기':'관리자 문의하기'}</h2>{report?<><label>신고 대상<input placeholder="닉네임 또는 사용자 ID를 입력해 주세요."/></label><label>신고 유형<select><option>경매 방해 행위</option><option>부적절한 메시지</option><option>사기 의심</option><option>기타</option></select></label></>:<label>문의 유형<select><option>경매 문의</option><option>배송 문의</option><option>결제 문의</option></select></label>}<label>{report?'신고 사유':'문의 내용'}<textarea placeholder={report?'신고 사유와 상황을 자세히 입력해 주세요.':'문의 내용을 입력해 주세요.'}/></label><button>{report?'유저 신고 접수':'문의 접수'}</button></section><SupportHistory report={report}/></div>}

function AccountField({label,value}){return <div className="account-field"><span><small>{label}</small><b>{value}</b></span><button>수정</button></div>}

function AccountView(){return <div className="mypage-subview"><div className="subview-title"><small>MY PAGE</small><h1>계정 관리</h1><p>회원 정보와 배송·연락처를 관리하세요.</p></div><section id="profile-info" className="subview-card"><h2>회원 정보</h2><AccountField label="이름" value="포켓컬렉터"/><AccountField label="이메일" value="jy•••••••@gmail.com"/></section><section id="shipping-address" className="subview-card"><h2>기본 배송지</h2><AccountField label="받는 분" value="포켓컬렉터"/><AccountField label="주소" value="서울시 성동구 성수이로 12길 24"/></section><section id="phone-info" className="subview-card"><h2>연락처</h2><AccountField label="휴대전화" value="010-1234-5678"/></section><section id="signout" className="subview-card signout-card"><span><b>로그아웃</b><small>현재 기기에서 안전하게 로그아웃합니다.</small></span><button>로그아웃</button></section></div>}

export default function MyPageThreeViews(){const[view,setView]=useState('account');const scroll=id=>document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'});const change=(next,target)=>{setView(next);if(target)setTimeout(()=>scroll(target),0)};return <div className="cards-mypage"><Header/><div className="cards-dash-shell"><ThreeViewNav view={view} onView={change} onScroll={scroll}/><main>{view==='support'?<SupportView/>:<AccountView/>}</main></div></div>}
